package com.cjy.flb.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BOX".
 */
public class Box {

    private Long boxId;
    /** Not-null value. */
    private String day_in_week;
    /** Not-null value. */
    private String point_in_time;
    private Integer number;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Box() {
    }

    public Box(Long boxId) {
        this.boxId = boxId;
    }

    public Box(Long boxId, String day_in_week, String point_in_time, Integer number) {
        this.boxId = boxId;
        this.day_in_week = day_in_week;
        this.point_in_time = point_in_time;
        this.number = number;
    }

    public Long getBoxId() {
        return boxId;
    }

    public void setBoxId(Long boxId) {
        this.boxId = boxId;
    }

    /** Not-null value. */
    public String getDay_in_week() {
        return day_in_week;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDay_in_week(String day_in_week) {
        this.day_in_week = day_in_week;
    }

    /** Not-null value. */
    public String getPoint_in_time() {
        return point_in_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPoint_in_time(String point_in_time) {
        this.point_in_time = point_in_time;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
