package com.cjy.flb.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EAT".
 */
public class Eat {

    private Long id;
    /** Not-null value. */
    private String device_uid;
    private String eat_medicine_time;
    private Integer number;
    private Boolean taken;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Eat() {
    }

    public Eat(Long id) {
        this.id = id;
    }

    public Eat(Long id, String device_uid, String eat_medicine_time, Integer number, Boolean taken) {
        this.id = id;
        this.device_uid = device_uid;
        this.eat_medicine_time = eat_medicine_time;
        this.number = number;
        this.taken = taken;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDevice_uid() {
        return device_uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDevice_uid(String device_uid) {
        this.device_uid = device_uid;
    }

    public String getEat_medicine_time() {
        return eat_medicine_time;
    }

    public void setEat_medicine_time(String eat_medicine_time) {
        this.eat_medicine_time = eat_medicine_time;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Boolean getTaken() {
        return taken;
    }

    public void setTaken(Boolean taken) {
        this.taken = taken;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
