package com.cjy.flb.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EAT_TIME".
 */
public class EatTime {

    private Long id;
    private String medic_id;
    private Long morn;
    private Long non;
    private Long after;
    private Long even;
    private String mornS;
    private String nonS;
    private String afterS;
    private String evenS;
    private String name;
    private String phone;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public EatTime() {
    }

    public EatTime(Long id) {
        this.id = id;
    }

    public EatTime(Long id, String medic_id, Long morn, Long non, Long after, Long even, String mornS, String nonS, String afterS, String evenS, String name, String phone) {
        this.id = id;
        this.medic_id = medic_id;
        this.morn = morn;
        this.non = non;
        this.after = after;
        this.even = even;
        this.mornS = mornS;
        this.nonS = nonS;
        this.afterS = afterS;
        this.evenS = evenS;
        this.name = name;
        this.phone = phone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMedic_id() {
        return medic_id;
    }

    public void setMedic_id(String medic_id) {
        this.medic_id = medic_id;
    }

    public Long getMorn() {
        return morn;
    }

    public void setMorn(Long morn) {
        this.morn = morn;
    }

    public Long getNon() {
        return non;
    }

    public void setNon(Long non) {
        this.non = non;
    }

    public Long getAfter() {
        return after;
    }

    public void setAfter(Long after) {
        this.after = after;
    }

    public Long getEven() {
        return even;
    }

    public void setEven(Long even) {
        this.even = even;
    }

    public String getMornS() {
        return mornS;
    }

    public void setMornS(String mornS) {
        this.mornS = mornS;
    }

    public String getNonS() {
        return nonS;
    }

    public void setNonS(String nonS) {
        this.nonS = nonS;
    }

    public String getAfterS() {
        return afterS;
    }

    public void setAfterS(String afterS) {
        this.afterS = afterS;
    }

    public String getEvenS() {
        return evenS;
    }

    public void setEvenS(String evenS) {
        this.evenS = evenS;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
