package com.cjy.flb.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "IS_NOTIF".
 */
public class IsNotif {

    private Long id;
    private String today;
    private String medic_id;
    private String medic_name;
    private String medic_phone;
    private Boolean isMOut;
    private Integer isM;
    private Boolean isNOut;
    private Integer isN;
    private Boolean isAOut;
    private Integer isA;
    private Boolean isEOut;
    private Integer isE;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IsNotif() {
    }

    public IsNotif(Long id) {
        this.id = id;
    }

    public IsNotif(Long id, String today, String medic_id, String medic_name, String medic_phone, Boolean isMOut,
                   Integer isM, Boolean isNOut, Integer isN, Boolean isAOut, Integer isA, Boolean isEOut, Integer isE) {
        this.id = id;
        this.today = today;
        this.medic_id = medic_id;
        this.medic_name = medic_name;
        this.medic_phone = medic_phone;
        this.isMOut = isMOut;
        this.isM = isM;
        this.isNOut = isNOut;
        this.isN = isN;
        this.isAOut = isAOut;
        this.isA = isA;
        this.isEOut = isEOut;
        this.isE = isE;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getToday() {
        return today;
    }

    public void setToday(String today) {
        this.today = today;
    }

    public String getMedic_id() {
        return medic_id;
    }

    public void setMedic_id(String medic_id) {
        this.medic_id = medic_id;
    }

    public String getMedic_name() {
        return medic_name;
    }

    public void setMedic_name(String medic_name) {
        this.medic_name = medic_name;
    }

    public String getMedic_phone() {
        return medic_phone;
    }

    public void setMedic_phone(String medic_phone) {
        this.medic_phone = medic_phone;
    }

    public Boolean getIsMOut() {
        return isMOut;
    }

    public void setIsMOut(Boolean isMOut) {
        this.isMOut = isMOut;
    }

    public Integer getIsM() {
        return isM;
    }

    public void setIsM(Integer isM) {
        this.isM = isM;
    }

    public Boolean getIsNOut() {
        return isNOut;
    }

    public void setIsNOut(Boolean isNOut) {
        this.isNOut = isNOut;
    }

    public Integer getIsN() {
        return isN;
    }

    public void setIsN(Integer isN) {
        this.isN = isN;
    }

    public Boolean getIsAOut() {
        return isAOut;
    }

    public void setIsAOut(Boolean isAOut) {
        this.isAOut = isAOut;
    }

    public Integer getIsA() {
        return isA;
    }

    public void setIsA(Integer isA) {
        this.isA = isA;
    }

    public Boolean getIsEOut() {
        return isEOut;
    }

    public void setIsEOut(Boolean isEOut) {
        this.isEOut = isEOut;
    }

    public Integer getIsE() {
        return isE;
    }

    public void setIsE(Integer isE) {
        this.isE = isE;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
