package com.cjy.flb.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "REPEAT_WEEK".
 */
public class RepeatWeek {

    private Long id;
    private String medic_id;
    private String number;
    private Boolean isEvery;
    private Boolean isMorn;
    private Boolean isTue;
    private Boolean isWed;
    private Boolean isThu;
    private Boolean isFri;
    private Boolean isSat;
    private Boolean isSun;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RepeatWeek() {
    }

    public RepeatWeek(Long id) {
        this.id = id;
    }

    public RepeatWeek(Long id, String medic_id, String number, Boolean isEvery, Boolean isMorn, Boolean isTue, Boolean isWed, Boolean isThu, Boolean isFri, Boolean isSat, Boolean isSun) {
        this.id = id;
        this.medic_id = medic_id;
        this.number = number;
        this.isEvery = isEvery;
        this.isMorn = isMorn;
        this.isTue = isTue;
        this.isWed = isWed;
        this.isThu = isThu;
        this.isFri = isFri;
        this.isSat = isSat;
        this.isSun = isSun;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMedic_id() {
        return medic_id;
    }

    public void setMedic_id(String medic_id) {
        this.medic_id = medic_id;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public Boolean getIsEvery() {
        return isEvery;
    }

    public void setIsEvery(Boolean isEvery) {
        this.isEvery = isEvery;
    }

    public Boolean getIsMorn() {
        return isMorn;
    }

    public void setIsMorn(Boolean isMorn) {
        this.isMorn = isMorn;
    }

    public Boolean getIsTue() {
        return isTue;
    }

    public void setIsTue(Boolean isTue) {
        this.isTue = isTue;
    }

    public Boolean getIsWed() {
        return isWed;
    }

    public void setIsWed(Boolean isWed) {
        this.isWed = isWed;
    }

    public Boolean getIsThu() {
        return isThu;
    }

    public void setIsThu(Boolean isThu) {
        this.isThu = isThu;
    }

    public Boolean getIsFri() {
        return isFri;
    }

    public void setIsFri(Boolean isFri) {
        this.isFri = isFri;
    }

    public Boolean getIsSat() {
        return isSat;
    }

    public void setIsSat(Boolean isSat) {
        this.isSat = isSat;
    }

    public Boolean getIsSun() {
        return isSun;
    }

    public void setIsSun(Boolean isSun) {
        this.isSun = isSun;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
