package com.cjy.flb.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cjy.flb.db.Box;
import com.cjy.flb.db.Eat;
import com.cjy.flb.db.IsNotif;
import com.cjy.flb.db.EatTime;
import com.cjy.flb.db.RepeatWeek;
import com.cjy.flb.db.SetMedicTime;

import com.cjy.flb.dao.BoxDao;
import com.cjy.flb.dao.EatDao;
import com.cjy.flb.dao.IsNotifDao;
import com.cjy.flb.dao.EatTimeDao;
import com.cjy.flb.dao.RepeatWeekDao;
import com.cjy.flb.dao.SetMedicTimeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig boxDaoConfig;
    private final DaoConfig eatDaoConfig;
    private final DaoConfig isNotifDaoConfig;
    private final DaoConfig eatTimeDaoConfig;
    private final DaoConfig repeatWeekDaoConfig;
    private final DaoConfig setMedicTimeDaoConfig;

    private final BoxDao boxDao;
    private final EatDao eatDao;
    private final IsNotifDao isNotifDao;
    private final EatTimeDao eatTimeDao;
    private final RepeatWeekDao repeatWeekDao;
    private final SetMedicTimeDao setMedicTimeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        boxDaoConfig = daoConfigMap.get(BoxDao.class).clone();
        boxDaoConfig.initIdentityScope(type);

        eatDaoConfig = daoConfigMap.get(EatDao.class).clone();
        eatDaoConfig.initIdentityScope(type);

        isNotifDaoConfig = daoConfigMap.get(IsNotifDao.class).clone();
        isNotifDaoConfig.initIdentityScope(type);

        eatTimeDaoConfig = daoConfigMap.get(EatTimeDao.class).clone();
        eatTimeDaoConfig.initIdentityScope(type);

        repeatWeekDaoConfig = daoConfigMap.get(RepeatWeekDao.class).clone();
        repeatWeekDaoConfig.initIdentityScope(type);

        setMedicTimeDaoConfig = daoConfigMap.get(SetMedicTimeDao.class).clone();
        setMedicTimeDaoConfig.initIdentityScope(type);

        boxDao = new BoxDao(boxDaoConfig, this);
        eatDao = new EatDao(eatDaoConfig, this);
        isNotifDao = new IsNotifDao(isNotifDaoConfig, this);
        eatTimeDao = new EatTimeDao(eatTimeDaoConfig, this);
        repeatWeekDao = new RepeatWeekDao(repeatWeekDaoConfig, this);
        setMedicTimeDao = new SetMedicTimeDao(setMedicTimeDaoConfig, this);

        registerDao(Box.class, boxDao);
        registerDao(Eat.class, eatDao);
        registerDao(IsNotif.class, isNotifDao);
        registerDao(EatTime.class, eatTimeDao);
        registerDao(RepeatWeek.class, repeatWeekDao);
        registerDao(SetMedicTime.class, setMedicTimeDao);
    }
    
    public void clear() {
        boxDaoConfig.getIdentityScope().clear();
        eatDaoConfig.getIdentityScope().clear();
        isNotifDaoConfig.getIdentityScope().clear();
        eatTimeDaoConfig.getIdentityScope().clear();
        repeatWeekDaoConfig.getIdentityScope().clear();
        setMedicTimeDaoConfig.getIdentityScope().clear();
    }

    public BoxDao getBoxDao() {
        return boxDao;
    }

    public EatDao getEatDao() {
        return eatDao;
    }

    public IsNotifDao getIsNotifDao() {
        return isNotifDao;
    }

    public EatTimeDao getEatTimeDao() {
        return eatTimeDao;
    }

    public RepeatWeekDao getRepeatWeekDao() {
        return repeatWeekDao;
    }

    public SetMedicTimeDao getSetMedicTimeDao() {
        return setMedicTimeDao;
    }

}
